Repository BookJamm/iOS, pull requests merged in 2023-08, with the labels that each got.

#26 Feat: 디테일 페이지 UI 구현 완료
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/Cell/BookActivityCollectionViewCell.swift
  Bookjam/Cell/BookStorePhotoCollectionViewCell.swift
  Bookjam/Cell/MainPageBookStoreTableViewCell.swift
  Bookjam/Screen/BookStoreDetailHomeView.swift
  Bookjam/View/MainPage/BookstoreDetailVC.swift
  Bookjam/View/MainPage/MainPageVC.swift
  Bookjam/View/Onboarding/Onboarding01VC.swift
Labels: 👾 Zimging, ⭐️ Feat, 🎨 UI

#30 [Refactor] 전체 프로젝트 주석 추가
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/Extension/UIImage+.swift
  Bookjam/Screen/Main/DetailPage/BookstoreDetailPageVC.swift
  Bookjam/Screen/Main/DetailPage/Cell/ActivityTableViewCell.swift
  Bookjam/Screen/Main/DetailPage/Cell/BookActivityCollectionViewCell.swift
  Bookjam/Screen/Main/DetailPage/Cell/BookListCollectionViewCell.swift
  Bookjam/Screen/Main/DetailPage/Cell/BookListTableViewCell.swift
  Bookjam/Screen/Main/DetailPage/Cell/BookStorePhotoCollectionViewCell.swift
  Bookjam/Screen/Main/DetailPage/Cell/NewsTableViewCell.swift
  Bookjam/Screen/Main/DetailPage/Cell/VisitReviewTableViewCell.swift
  Bookjam/Screen/Main/DetailPage/View/BookStoreDetailActivityView.swift
  Bookjam/Screen/Main/DetailPage/View/BookStoreDetailBookListView.swift
  Bookjam/Screen/Main/DetailPage/View/BookStoreDetailHomeView.swift
  Bookjam/Screen/Main/DetailPage/View/BookStoreDetailNewsView.swift
  Bookjam/Screen/Main/DetailPage/View/BookStoreDetailReviewView.swift
  Bookjam/Screen/Main/FeedPage/FeedPageVC.swift
  Bookjam/Screen/Main/LocationPage/LocationPageVC.swift
  Bookjam/Screen/Main/MainPage/Cell/MainPageBookStoreTableViewCell.swift
  Bookjam/Screen/Main/MainPage/MainPageVC.swift
  Bookjam/Screen/Main/MyPage/MyPageVC.swift
  Bookjam/Screen/Main/TabBarController.swift
  Bookjam/Screen/Onboarding/Onboarding02VC.swift
  Bookjam/Screen/ViewController.swift
Labels: 👾 Zimging, ♻️ Refactor

#32 [Feat] 유저 페이지 & 프로필 설정 화면 구현
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/Resource/Assets.xcassets/Resources/MyPage/Contents.json
  Bookjam/Resource/Assets.xcassets/Resources/MyPage/profilePlusButton.imageset/Contents.json
  Bookjam/Resource/Assets.xcassets/Resources/MyPage/profilePlusButton.imageset/profilePlusButton.svg
  Bookjam/Screen/Main/MyPage/ChangeProfileVC.swift
  Bookjam/Screen/Main/MyPage/UserPageVC.swift
  Bookjam/Screen/ViewController.swift
Labels: 👾 Zimging, ⭐️ Feat, 🎨 UI

#36 Feat: 로그인 화면 UI 구현 완료
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/AppDelegate.swift
  Bookjam/Screen/Login/LoginVC.swift
  Bookjam/Screen/Onboarding/Onboarding01VC.swift
Labels: 👾 Zimging, ⭐️ Feat, 🎨 UI

#42 Feat: 메인 페이지 UI 구현 (1/2)
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/API/LoginAPI.swift
  Bookjam/Screen/Main/MainDetailPage/Activity/BookStoreActvityDetailVC.swift
  Bookjam/Screen/Main/MainDetailPage/Activity/Cell/ActivityTableViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Activity/View/BookStoreDetailActivityView.swift
  Bookjam/Screen/Main/MainDetailPage/BookList/Cell/BookListTableViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/BookList/View/BookStoreDetailBookListView.swift
  Bookjam/Screen/Main/MainDetailPage/BookstoreDetailPageVC.swift
  Bookjam/Screen/Main/MainDetailPage/Cell/VisitReviewTableViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Home/Cell/BookActivityCollectionViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Home/Cell/BookListCollectionViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Home/Cell/BookStorePhotoCollectionViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Home/View/BookStoreDetailHomeView.swift
  Bookjam/Screen/Main/MainDetailPage/News/Cell/NewsTableViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/News/View/BookStoreDetailNewsView.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreChoiceDateVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreReviewDetailVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreWriteReviewVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/View/BookStoreDetailReviewView.swift
  Bookjam/Screen/Main/MainDetailPage/Review/View/ChoiceDateBottomSheetVC.swift
  Bookjam/Screen/Main/MainPage/MainPageVC.swift
  Bookjam/Screen/Main/MyPage/MyPageVC.swift
  Bookjam/Screen/Main/MyPage/UserPageVC.swift
Labels: 👾 Zimging, ⭐️ Feat, ♻️ Refactor, 🎨 UI

#43 Feat: 리뷰 플로우 구현 완료
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/Resource/Assets.xcassets/Resources/HomeDetail/ReviewDoneToast.imageset/Contents.json
  Bookjam/Resource/Assets.xcassets/Resources/HomeDetail/ReviewDoneToast.imageset/ReviewDoneToast.svg
  Bookjam/Screen/Main/MainDetailPage/Activity/BookStoreActvityDetailVC.swift
  Bookjam/Screen/Main/MainDetailPage/Activity/Cell/ActivityTableViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Activity/View/BookStoreDetailActivityView.swift
  Bookjam/Screen/Main/MainDetailPage/BookstoreDetailPageVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreChoiceDateVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreReviewDetailVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreWriteReviewVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/Cell/VisitReviewPhotoCollectionViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Review/View/BookStoreDetailReviewView.swift
  Bookjam/Screen/Main/MainDetailPage/Review/View/ChoiceDateBottomSheetVC.swift
  Bookjam/Screen/Main/MainPage/MainPageVC.swift
  Bookjam/Screen/Main/MyPage/Cell/ActivityParticipateCollectionViewCell.swift
  Bookjam/Screen/Main/MyPage/MyPageVC.swift
  Bookjam/Screen/Main/TabBarController.swift
Labels: 👾 Zimging, ⭐️ Feat, 🎨 UI

#44 Feat: 로그인 API 구현
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/API/APIConstant.swift
  Bookjam/API/Entity/Login.swift
  Bookjam/Resource/Model/UserInfo.swift
  Bookjam/Screen/Login/LoginVC.swift
  Bookjam/Screen/Onboarding/Onboarding07VC.swift
  Bookjam/Screen/Onboarding/Onboarding08VC.swift
  Bookjam/Screen/Onboarding/Onboarding09VC.swift
Labels: 👾 Zimging, ⭐️ Feat, 🎨 UI

#45 Feat: 메인 UI 구현 완료
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/Screen/Main/MainPage/MainPageVC.swift
  Bookjam/Screen/Main/SearchPage/Cell/SearchResultTableViewCell.swift
  Bookjam/Screen/Main/SearchPage/SearchEnterResultVC.swift
  Bookjam/Screen/Main/SearchPage/SearchPageVC.swift
  Bookjam/Screen/Onboarding/Onboarding01VC.swift
Labels: 👾 Zimging, ⭐️ Feat, 🎨 UI

#47 Feat: 피드 검색 플로우 구현 중
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/Screen/Main/FeedPage/BookPostDetailVC.swift
  Bookjam/Screen/Main/FeedPage/Cell/FeedPostTableViewCell.swift
  Bookjam/Screen/Main/FeedPage/Cell/FeedUserTableViewCell.swift
  Bookjam/Screen/Main/FeedPage/Cell/ReviewTableViewCell.swift
  Bookjam/Screen/Main/FeedPage/FeedPageVC.swift
  Bookjam/Screen/Main/FeedPage/UserSearchPageVC.swift
  Bookjam/Screen/Main/MainPage/MainPageVC.swift
  Bookjam/Screen/TableViewCell.swift
  Bookjam/Screen/ViewController.swift
Labels: 👾 Zimging, 🎨 UI

#49 Feat/41 mainpage api 연결
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/API/APIConstant.swift
  Bookjam/API/APIManager.swift
  Bookjam/API/Entity/GetPlaces.swift
  Bookjam/API/Entity/KeywordSearch.swift
  Bookjam/API/Entity/SingUp.swift
  Bookjam/Screen/Main/MainPage/MainPageVC.swift
  Bookjam/Screen/Main/SearchPage/SearchEnterResultVC.swift
  Bookjam/Screen/Main/SearchPage/SearchPageVC.swift
Labels: 😎 Jangmo, ⭐️ Feat

#50 Feat: 글 작성 페이지 UI 구현
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/API/APIConstant.swift
  Bookjam/API/Entity/Record.swift
  Bookjam/Screen/Main/FeedPage/Cell/PlaceSearchTableViewCell.swift
  Bookjam/Screen/Main/FeedPage/FeedPostCheckPopUpVC.swift
  Bookjam/Screen/Main/FeedPage/FeedPostPageVC.swift
  Bookjam/Screen/Main/FeedPage/SearchActivityPopUpVC.swift
  Bookjam/Screen/Main/FeedPage/SearchBookPopUpVC.swift
  Bookjam/Screen/Main/FeedPage/SearchPlacePopUpVC.swift
  Bookjam/Screen/Main/FeedPage/SelectVisitDatePopUpVC.swift
  Bookjam/Screen/Main/SearchPage/SearchPageVC.swift
  Bookjam/Screen/TableViewCell.swift
Labels: 👾 Zimging, ⭐️ Feat, 🎨 UI

#52 Fix: UI 추가 구현 및 오류 수정
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/API/APIConstant.swift
  Bookjam/API/Entity/RecommendFriend.swift
  Bookjam/API/Entity/SearchFriend.swift
  Bookjam/Extension/UIViewController+.swift
  Bookjam/Screen/Main/FeedPage/BookPostDetailVC.swift
  Bookjam/Screen/Main/FeedPage/FeedPostCheckPopUpVC.swift
  Bookjam/Screen/Main/FeedPage/SearchActivityPopUpVC.swift
  Bookjam/Screen/Main/FeedPage/SearchBookPopUpVC.swift
  Bookjam/Screen/Main/FeedPage/SearchPlacePopUpVC.swift
  Bookjam/Screen/Main/FeedPage/SelectVisitDatePopUpVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreWriteReviewVC.swift
  Bookjam/Screen/Main/TabBarController.swift
  Bookjam/Screen/Onboarding/Onboarding03VC.swift
  Bookjam/Screen/Onboarding/Onboarding04VC.swift
  Bookjam/Screen/Onboarding/Onboarding05/Cell/FriendInfoTableViewCell.swift
  Bookjam/Screen/Onboarding/Onboarding05/Onboarding05VC.swift
  Bookjam/Screen/Onboarding/Onboarding05/View/Onboarding05BottomSheet.swift
Labels: 👾 Zimging, 🐞 Bug, ⭐️ Feat, 🎨 UI

#58 Feat: 리뷰 API 연결
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/API/APIConstant.swift
  Bookjam/API/APIManager.swift
  Bookjam/API/Entity/ReviewContent.swift
  Bookjam/API/Entity/ReviewImage.swift
  Bookjam/API/LoginAPI.swift
  Bookjam/Screen/Login/LoginVC.swift
  Bookjam/Screen/Main/FeedPage/SearchPlacePopUpVC.swift
  Bookjam/Screen/Main/MainDetailPage/BookstoreDetailPageVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreChoiceDateVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreReviewDetailVC.swift
  Bookjam/Screen/Main/MainDetailPage/Review/BookStoreWriteReviewVC.swift
  Bookjam/Screen/Main/SearchPage/SearchPageVC.swift
  Bookjam/Screen/Onboarding/Onboarding01VC.swift
  Bookjam/Screen/Onboarding/Onboarding03VC.swift
  Bookjam/Screen/Onboarding/Onboarding05/Onboarding05VC.swift
Labels: 👾 Zimging, 🐞 Bug, ⭐️ Feat

#63 Feature/54 maindetail page api
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/API/Entity/PlaceIdActivities.swift
  Bookjam/API/Entity/PlaceIdBooks.swift
  Bookjam/Screen/Main/MainDetailPage/Activity/View/BookStoreDetailActivityView.swift
  Bookjam/Screen/Main/MainDetailPage/BookList/Cell/BookListTableViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/BookList/View/BookStoreDetailBookListView.swift
  Bookjam/Screen/Main/MainDetailPage/BookstoreDetailPageVC.swift
  Bookjam/Screen/Main/MainDetailPage/Home/Cell/BookListCollectionViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Home/View/BookStoreDetailHomeView.swift
  Bookjam/Screen/Main/MainDetailPage/News/View/BookStoreDetailNewsView.swift
  Bookjam/Screen/Main/MainPage/MainPageInfoViewController.swift
Labels: 😎 Jangmo, ⭐️ Feat

#64 Feat: 마이페이지 API 연결
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/API/APIConstant.swift
  Bookjam/API/Entity/RecommendFriend.swift
  Bookjam/API/Entity/UsersActivities.swift
  Bookjam/API/Entity/UsersOutline.swift
  Bookjam/API/Entity/UsersRecords.swift
  Bookjam/API/Entity/UsersReviews.swift
  Bookjam/Screen/Main/FeedPage/SearchBookPopUpVC.swift
  Bookjam/Screen/Main/MainDetailPage/Home/Cell/BookStorePhotoCollectionViewCell.swift
  Bookjam/Screen/Main/MainPage/Cell/MainPageBookStoreTableViewCell.swift
  Bookjam/Screen/Main/MainPage/MainPageVC.swift
  Bookjam/Screen/Main/MyPage/MyPageVC.swift
  Bookjam/Screen/Main/TabBarController.swift
  Bookjam/Screen/Onboarding/Onboarding05/Onboarding05VC.swift
Labels: 👾 Zimging, 🐞 Bug, ⭐️ Feat

#73 Test: PR 테스트용
  Bookjam/API/APIManager.swift
Labels: 👾 Zimging, ⚙️ Chore

#76 Feat: 폰트 수정
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/Resource/Data/FontData.swift
  Bookjam/Resource/Font/SUIT-Variable.ttf
  Bookjam/Resource/Info.plist
  Bookjam/Screen/Onboarding/Onboarding01VC.swift
  Bookjam/Screen/Onboarding/Onboarding03VC.swift
  Bookjam/Screen/Onboarding/Onboarding04VC.swift
  Bookjam/Screen/Onboarding/Onboarding05/Cell/FriendInfoTableViewCell.swift
  Bookjam/Screen/Onboarding/Onboarding05/Onboarding05VC.swift
  Bookjam/Screen/Onboarding/Onboarding05/RecommendFriendPopUpVC.swift
  Bookjam/Screen/Onboarding/Onboarding06VC.swift
  Bookjam/Screen/Onboarding/Onboarding07VC.swift
  Bookjam/Screen/Onboarding/Onboarding08VC.swift
  Bookjam/Screen/Onboarding/Onboarding09VC.swift
Labels: 👾 Zimging, 🎨 UI

#78 Feat : 지도 화면 UI 구현 완료
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/Screen/Main/LocationPage/BaseBottomSheetController.swift
  Bookjam/Screen/Main/LocationPage/BookStoreListVC.swift
  Bookjam/Screen/Main/LocationPage/Cell/LocationTableViewCell.swift
  Bookjam/Screen/Main/LocationPage/LocationPageVC.swift
  Bookjam/Screen/Main/LocationPage/View/CustomAnnotationView.swift
  Bookjam/Screen/Main/LocationPage/View/MapClusterView.swift
  Bookjam/Screen/Main/TabBarController.swift
Labels: ⭐️ Feat, 🎨 UI, 🛋️ Lamp
