Repository BookJamm/iOS, pull requests merged in 2023-09, with the labels that each got.

#81 Feat : 지도 화면 API 구현
  Bookjam/API/Entity/GetPlaces.swift
  Bookjam/Screen/Main/LocationPage/BookStoreListVC.swift
  Bookjam/Screen/Main/LocationPage/Cell/LocationTableViewCell.swift
  Bookjam/Screen/Main/LocationPage/LocationPageVC.swift
  Bookjam/Screen/Main/MainDetailPage/BookstoreDetailPageVC.swift
  Bookjam/Screen/Main/TabBarController.swift
Labels: ⭐️ Feat, 🛋️ Lamp

#83 Feature/82 location page refine
  Bookjam.xcodeproj/project.pbxproj
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/Contents.json
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/bookPin.imageset/Contents.json
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/bookPin.imageset/bookPin 1.svg
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/bookPin.imageset/bookPin 2.svg
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/bookPin.imageset/bookPin.svg
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/coffeePin.imageset/Contents.json
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/coffeePin.imageset/coffeePin 1.svg
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/coffeePin.imageset/coffeePin 2.svg
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/coffeePin.imageset/coffeePin.svg
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/libraryPin.imageset/Contents.json
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/libraryPin.imageset/booksPin 1.svg
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/libraryPin.imageset/booksPin 2.svg
  Bookjam/Resource/Assets.xcassets/Resources/LocationPage/libraryPin.imageset/booksPin.svg
  Bookjam/Screen/Main/LocationPage/BookStoreListVC.swift
  Bookjam/Screen/Main/LocationPage/Cell/LocationTableViewCell.swift
  Bookjam/Screen/Main/LocationPage/LocationPageVC.swift
  Bookjam/Screen/Main/LocationPage/Model/LocationCategoryModel.swift
  Bookjam/Screen/Main/LocationPage/Model/filterModel.swift
  Bookjam/Screen/Main/LocationPage/View/ColorToggleButton.swift
  Bookjam/Screen/Main/LocationPage/View/CustomAnnotationView.swift
Labels: ⭐️ Feat, 🎨 UI, 🛋️ Lamp

#85 Fix: 프로젝트 전체 수정
  Bookjam/API/APIManager.swift
  Bookjam/Extension/UIView+.swift
  Bookjam/Resource/Assets.xcassets/Resources/HomeDetail/squareDefaultImage.imageset/Contents.json
  Bookjam/Resource/Assets.xcassets/Resources/HomeDetail/squareDefaultImage.imageset/squareDefaultImage.svg
  Bookjam/Resource/Assets.xcassets/Resources/HomeDetail/squareDefaultImage.imageset/user defualt profile.svg
  Bookjam/Screen/Login/LoginVC.swift
  Bookjam/Screen/Main/FeedPage/Cell/FeedPostTableViewCell.swift
  Bookjam/Screen/Main/FeedPage/Cell/PlaceSearchTableViewCell.swift
  Bookjam/Screen/Main/FeedPage/FeedPageVC.swift
  Bookjam/Screen/Main/FeedPage/FeedPostPageVC.swift
  Bookjam/Screen/Main/FeedPage/UserSearchPageVC.swift
  Bookjam/Screen/Main/LocationPage/BookStoreListVC.swift
  Bookjam/Screen/Main/LocationPage/Cell/LocationTableViewCell.swift
  Bookjam/Screen/Main/LocationPage/View/ColorToggleButton.swift
  Bookjam/Screen/Main/MainDetailPage/Activity/Cell/ActivityTableViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Activity/View/BookStoreDetailActivityView.swift
  Bookjam/Screen/Main/MainDetailPage/BookList/View/BookStoreDetailBookListView.swift
  Bookjam/Screen/Main/MainDetailPage/BookstoreDetailPageVC.swift
  Bookjam/Screen/Main/MainDetailPage/Cell/VisitReviewTableViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Home/Cell/BookListCollectionViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/Home/View/BookStoreDetailHomeView.swift
  Bookjam/Screen/Main/MainDetailPage/News/Cell/NewsTableViewCell.swift
  Bookjam/Screen/Main/MainDetailPage/News/View/BookStoreDetailNewsView.swift
  Bookjam/Screen/Main/MainDetailPage/Review/View/BookStoreDetailReviewView.swift
  Bookjam/Screen/Main/MainPage/Cell/MainPageBookStoreTableViewCell.swift
  Bookjam/Screen/Main/MainPage/MainPageVC.swift
  Bookjam/Screen/Main/MyPage/Cell/ActivityParticipateCollectionViewCell.swift
  Bookjam/Screen/Main/MyPage/MyPageVC.swift
  Bookjam/Screen/Main/MyPage/UserPageVC.swift
  Bookjam/Screen/Main/MyPage/View/MyRecordBookStoreView.swift
  Bookjam/Screen/Main/TabBarController.swift
  Bookjam/Screen/Onboarding/Onboarding01VC.swift
  Bookjam/Screen/Onboarding/Onboarding05/Onboarding05VC.swift
  Bookjam/Screen/Onboarding/Onboarding05/RecommendFriendPopUpVC.swift
Labels: 👾 Zimging, 🐞 Bug, ⭐️ Feat, ♻️ Refactor, 🎨 UI
